# ...existing code...
Export-ModuleMember -Function Get-GitStrategy, Get-CurrentBranch, New-GitBranch, New-GitBranchName, New-Workspace, Set-Workspace, New-Repository, Get-Repository, Set-Repository, Get-TemporaryBranch, Get-GitBranch, Get-RepositoryStatus, Set-Branch, Set-GitStrategy, Get-MainBranch, Set-CommitBranch, Set-TemporaryStash, Update-AllRepositoriesMain, Update-Workspace
# ...existing code...
