# ...existing code...
Export-ModuleMember -Function Get-CurrentBranch, Get-GitStrategy, Get-MainBranch, Get-RepositoryStatus, Get-TemporaryStash, Get-Workspace, New-Branch, New-Repository, Set-Branch, Set-CommitBranch, Set-GitStrategy, Set-TemporaryStash, Update-AllRepositoriesMain, Update-OriginRepository, Update-Workspace
# ...existing code...
