name: Pester Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run Pester tests
      run: Invoke-Pester -Script ./WorkspaceManagement/Tests/Tests/*.Tests.ps1
